# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

"""Operator: activation_norm/silu_and_mul (generic placeholder).

Gated SiLU activation:
    out = silu(hidden_states[..., :d]) * hidden_states[..., d:]
where ``d = hidden_states.shape[-1] // 2``.

This is a placeholder registration for the generic (device-agnostic)
Triton tier. Replace the body of :func:`silu_and_mul` with the actual
kernel invocation.
"""

import torch


def silu_and_mul(hidden_states: torch.Tensor) -> torch.Tensor:
    """Gated SiLU: ``silu(x[..., :d]) * x[..., d:]``.

    Args:
        hidden_states: Input tensor with an even last dimension.

    Returns:
        Tensor with the last dim halved, same dtype as ``hidden_states``.
    """
    raise NotImplementedError(
        "silu_and_mul generic Triton kernel is not implemented yet."
    )


__all__ = ["silu_and_mul"]
