# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen


"""Kunlunxin loop scan with aligned output storage and XPU scheduling."""


import torch
import triton
import triton.language as tl

__all__ = ["chunk_cumsum"]


@triton.jit
def _softplus_fp32(x):
    # max(x, 0) + log(1 + exp(-abs(x))) is stable at both tails.
    return tl.maximum(x, 0.0) + tl.log(1.0 + tl.exp(-tl.abs(x)))


@triton.jit(do_not_specialize=["seqlen"])
def _chunk_cumsum_xpu_loop_kernel(
    dt_ptr,
    a_ptr,
    bias_ptr,
    dt_out_ptr,
    da_cumsum_ptr,
    seqlen,
    total_rows: tl.constexpr,
    nheads: tl.constexpr,
    nchunks: tl.constexpr,
    chunk_size: tl.constexpr,
    stride_dt_b: tl.constexpr,
    stride_dt_s: tl.constexpr,
    stride_dt_h: tl.constexpr,
    stride_a_h: tl.constexpr,
    stride_bias_h: tl.constexpr,
    HAS_BIAS: tl.constexpr,
    DT_SOFTPLUS: tl.constexpr,
    BLOCK_R: tl.constexpr,
):
    # XPU's ScanOp lowering uses a fixed 64-element shared-memory scratch and
    # several whole-core barriers.  Flatten all independent (batch, chunk,
    # head) recurrences into one row axis, then carry several scalar
    # recurrences per XPU core.  A large 1-D tile matches FlagGems' Kunlun
    # pointwise scheduling: fewer logical programs are distributed over the
    # 12 clusters by FlagTree's LoopGrid pass, while no ScanOp is emitted.
    pid_r = tl.program_id(0)
    offs_r = pid_r * BLOCK_R + tl.arange(0, BLOCK_R)
    valid_r = offs_r < total_rows

    # Flatten in [batch, chunk, head] order so the overwhelmingly common
    # interior lanes still read adjacent heads from the [B, S, H] input.
    offs_h = offs_r % nheads
    offs_bc = offs_r // nheads
    pid_c = offs_bc % nchunks
    pid_b = offs_bc // nchunks

    a = tl.load(
        a_ptr + offs_h * stride_a_h,
        mask=valid_r,
        other=0.0,
    ).to(tl.float32)

    if HAS_BIAS:
        bias = tl.load(
            bias_ptr + offs_h * stride_bias_h,
            mask=valid_r,
            other=0.0,
        ).to(tl.float32)
    else:
        bias = tl.zeros((BLOCK_R,), tl.float32)

    running = tl.zeros((BLOCK_R,), tl.float32)
    for k in range(0, chunk_size):
        offs_s = pid_c * chunk_size + k
        load_mask = valid_r & (offs_s < seqlen)
        dt_offsets = (
            pid_b * stride_dt_b + offs_s * stride_dt_s + offs_h * stride_dt_h
        )
        dt = tl.load(
            dt_ptr + dt_offsets,
            mask=load_mask,
            other=0.0,
        ).to(tl.float32)
        dt += bias

        if DT_SOFTPLUS:
            dt = tl.where(dt <= 20.0, _softplus_fp32(dt), dt)

        dt = tl.maximum(dt, 0.0)
        # Bias / softplus may turn an out-of-sequence zero into a nonzero.
        dt = tl.where(load_mask, dt, 0.0)
        out_offsets = (
            (pid_b * nheads + offs_h) * nchunks + pid_c
        ) * chunk_size + k
        tl.store(dt_out_ptr + out_offsets, dt, mask=valid_r)

        running += dt * a
        tl.store(da_cumsum_ptr + out_offsets, running, mask=valid_r)


def chunk_cumsum(dt, A, chunk_size, dt_bias=None, dt_softplus=False):
    """Triton implementation of Mamba's chunk-wise dt/A cumulative sum."""
    if dt.ndim != 3:
        raise ValueError("dt must have shape [batch, seqlen, nheads]")
    if chunk_size <= 0:
        raise ValueError("chunk_size must be positive")
    (batch, seqlen, nheads) = dt.shape
    if seqlen == 0 or nheads == 0 or batch == 0:
        raise ValueError("dt dimensions must be nonzero")
    if A.ndim != 1 or A.shape[0] != nheads:
        raise ValueError("A must have shape [nheads]")
    if dt_bias is not None and (
        dt_bias.ndim != 1 or dt_bias.shape[0] != nheads
    ):
        raise ValueError("dt_bias must have shape [nheads]")
    nchunks = (seqlen + chunk_size - 1) // chunk_size
    out_shape = (batch, nheads, nchunks, chunk_size)
    # Both outputs share one allocation, with 16-byte-aligned starts.
    out_numel = batch * nheads * nchunks * chunk_size
    aligned_numel = out_numel + 3 & -4
    out_storage = torch.empty(
        2 * aligned_numel + 3, device=dt.device, dtype=torch.float32
    )
    base_shift = -(out_storage.data_ptr() // 4) & 3
    dt_out = out_storage[base_shift : base_shift + out_numel].view(out_shape)
    da_start = base_shift + aligned_numel
    da_cumsum = out_storage[da_start : da_start + out_numel].view(out_shape)
    bias_ptr = dt if dt_bias is None else dt_bias
    total_rows = batch * nchunks * nheads
    # Preserve the tuned 12-cluster schedule and recurrence-state cap.
    total_values = total_rows * chunk_size
    if total_values <= 64 * 2048:
        rows_per_program = total_rows
    else:
        rows_per_program = triton.cdiv(total_rows, 12)
    xpu_block_r = min(1024, triton.next_power_of_2(max(1, rows_per_program)))
    xpu_grid = (triton.cdiv(total_rows, xpu_block_r),)
    _chunk_cumsum_xpu_loop_kernel[xpu_grid](
        dt,
        A,
        bias_ptr,
        dt_out,
        da_cumsum,
        seqlen,
        total_rows,
        nheads,
        nchunks,
        chunk_size,
        dt.stride(0),
        dt.stride(1),
        dt.stride(2),
        A.stride(0),
        0 if dt_bias is None else dt_bias.stride(0),
        HAS_BIAS=dt_bias is not None,
        DT_SOFTPLUS=dt_softplus,
        BLOCK_R=xpu_block_r,
        isCloseUnrollControl=True,
    )
    return (dt_out, da_cumsum)
