# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

"""Tests for fused_moe_router_cudacore operator."""

import pytest
import torch

import flaggems_sglang
from flaggems_sglang.ops.fused_moe_router_cudacore import fused_moe_router_cudacore


def reference(x, router_weight, topk, moe_softcapping, correction_bias=None):
    """Reference implementation from competition problem statement."""
    logits = x.float() @ router_weight.float().t()
    if moe_softcapping != 0:
        logits = torch.tanh(logits / moe_softcapping) * moe_softcapping
    if correction_bias is not None:
        logits = logits + correction_bias.float()

    probs = torch.softmax(logits, dim=-1)
    topk_logits, topk_ids = torch.topk(logits, topk, dim=-1)
    topk_weights = torch.gather(probs, -1, topk_ids)

    return topk_weights, topk_ids.to(torch.int32)


# Test configurations
BATCH_SIZES = [1, 4, 8, 16]
HIDDEN_DIMS = [64, 128, 256, 512]
EXPERT_COUNTS = [8, 16, 32, 64]
TOPK_VALUES = [1, 2, 4]
SOFTCAPPING_VALUES = [0.0, 1.0, 10.0]
DTYPES = [torch.float32, torch.float16, torch.bfloat16]


@pytest.mark.fused_moe_router_cudacore
@pytest.mark.parametrize("B", BATCH_SIZES)
@pytest.mark.parametrize("H", HIDDEN_DIMS)
@pytest.mark.parametrize("E", EXPERT_COUNTS)
@pytest.mark.parametrize("topk", TOPK_VALUES)
@pytest.mark.parametrize("moe_softcapping", SOFTCAPPING_VALUES)
@pytest.mark.parametrize("dtype", DTYPES)
def test_fused_moe_router_cudacore_basic(B, H, E, topk, moe_softcapping, dtype):
    """Test basic functionality with various configurations."""
    if topk > E:
        pytest.skip(f"topk ({topk}) > E ({E})")
    
    # Create inputs
    x = torch.randn(B, H, dtype=dtype, device=flaggems_sglang.device)
    router_weight = torch.randn(E, H, dtype=dtype, device=flaggems_sglang.device)
    
    # Run reference
    ref_weights, ref_ids = reference(x, router_weight, topk, moe_softcapping)
    
    # Run implementation
    impl_weights, impl_ids = fused_moe_router_cudacore(x, router_weight, topk, moe_softcapping)
    
    # Check shapes
    assert impl_weights.shape == (B, topk), f"Expected shape ({B}, {topk}), got {impl_weights.shape}"
    assert impl_ids.shape == (B, topk), f"Expected shape ({B}, {topk}), got {impl_ids.shape}"
    
    # Check dtypes
    assert impl_weights.dtype == torch.float32, f"Expected float32, got {impl_weights.dtype}"
    assert impl_ids.dtype == torch.int32, f"Expected int32, got {impl_ids.dtype}"
    
    # Check values with tolerance based on dtype
    if dtype == torch.float32:
        atol, rtol = 1e-4, 1e-4
    elif dtype == torch.float16:
        atol, rtol = 1e-2, 1e-2
    elif dtype == torch.bfloat16:
        atol, rtol = 1.5e-2, 1.5e-2
    else:
        atol, rtol = 1e-4, 1e-4
    
    # Check topk_ids (exact match required)
    torch.testing.assert_close(impl_ids, ref_ids, atol=0, rtol=0)
    
    # Check topk_weights
    torch.testing.assert_close(impl_weights, ref_weights, atol=atol, rtol=rtol)


@pytest.mark.fused_moe_router_cudacore
@pytest.mark.parametrize("B", [4, 8])
@pytest.mark.parametrize("H", [128, 256])
@pytest.mark.parametrize("E", [16, 32])
@pytest.mark.parametrize("topk", [2, 4])
@pytest.mark.parametrize("dtype", [torch.float32, torch.float16])
def test_fused_moe_router_cudacore_with_correction_bias(B, H, E, topk, dtype):
    """Test with correction bias."""
    if topk > E:
        pytest.skip(f"topk ({topk}) > E ({E})")
    
    # Create inputs
    x = torch.randn(B, H, dtype=dtype, device=flaggems_sglang.device)
    router_weight = torch.randn(E, H, dtype=dtype, device=flaggems_sglang.device)
    correction_bias = torch.randn(E, dtype=torch.float32, device=flaggems_sglang.device)
    
    # Run reference
    ref_weights, ref_ids = reference(x, router_weight, topk, 0.0, correction_bias)
    
    # Run implementation
    impl_weights, impl_ids = fused_moe_router_cudacore(x, router_weight, topk, 0.0, correction_bias)
    
    # Check values with tolerance based on dtype
    if dtype == torch.float32:
        atol, rtol = 1e-4, 1e-4
    elif dtype == torch.float16:
        atol, rtol = 1e-2, 1e-2
    elif dtype == torch.bfloat16:
        atol, rtol = 1.5e-2, 1.5e-2
    else:
        atol, rtol = 1e-4, 1e-4
    
    # Check topk_ids (exact match required)
    torch.testing.assert_close(impl_ids, ref_ids, atol=0, rtol=0)
    
    # Check topk_weights
    torch.testing.assert_close(impl_weights, ref_weights, atol=atol, rtol=rtol)


@pytest.mark.fused_moe_router_cudacore
@pytest.mark.parametrize("B", [1, 4])
@pytest.mark.parametrize("H", [64, 128])
@pytest.mark.parametrize("E", [8, 16])
@pytest.mark.parametrize("topk", [1, 2])
@pytest.mark.parametrize("moe_softcapping", [1.0, 5.0, 10.0])
@pytest.mark.parametrize("dtype", [torch.float32, torch.float16])
def test_fused_moe_router_cudacore_with_softcapping(B, H, E, topk, moe_softcapping, dtype):
    """Test with soft-capping enabled."""
    if topk > E:
        pytest.skip(f"topk ({topk}) > E ({E})")
    
    # Create inputs
    x = torch.randn(B, H, dtype=dtype, device=flaggems_sglang.device)
    router_weight = torch.randn(E, H, dtype=dtype, device=flaggems_sglang.device)
    
    # Run reference
    ref_weights, ref_ids = reference(x, router_weight, topk, moe_softcapping)
    
    # Run implementation
    impl_weights, impl_ids = fused_moe_router_cudacore(x, router_weight, topk, moe_softcapping)
    
    # Check values with tolerance based on dtype
    if dtype == torch.float32:
        atol, rtol = 1e-4, 1e-4
    elif dtype == torch.float16:
        atol, rtol = 1e-2, 1e-2
    elif dtype == torch.bfloat16:
        atol, rtol = 1.5e-2, 1.5e-2
    else:
        atol, rtol = 1e-4, 1e-4
    
    # Check topk_ids (exact match required)
    torch.testing.assert_close(impl_ids, ref_ids, atol=0, rtol=0)
    
    # Check topk_weights
    torch.testing.assert_close(impl_weights, ref_weights, atol=atol, rtol=rtol)


@pytest.mark.fused_moe_router_cudacore
def test_fused_moe_router_cudacore_edge_cases():
    """Test edge cases."""
    B, H, E, topk = 2, 64, 8, 2
    dtype = torch.float32
    
    # Test with zero softcapping
    x = torch.randn(B, H, dtype=dtype, device=flaggems_sglang.device)
    router_weight = torch.randn(E, H, dtype=dtype, device=flaggems_sglang.device)
    
    ref_weights, ref_ids = reference(x, router_weight, topk, 0.0)
    impl_weights, impl_ids = fused_moe_router_cudacore(x, router_weight, topk, 0.0)
    
    torch.testing.assert_close(impl_ids, ref_ids, atol=0, rtol=0)
    torch.testing.assert_close(impl_weights, ref_weights, atol=1e-4, rtol=1e-4)
    
    # Test with very small softcapping
    ref_weights, ref_ids = reference(x, router_weight, topk, 0.1)
    impl_weights, impl_ids = fused_moe_router_cudacore(x, router_weight, topk, 0.1)
    
    torch.testing.assert_close(impl_ids, ref_ids, atol=0, rtol=0)
    torch.testing.assert_close(impl_weights, ref_weights, atol=1e-4, rtol=1e-4)


@pytest.mark.fused_moe_router_cudacore
def test_fused_moe_router_cudacore_numerical_stability():
    """Test numerical stability with large logits."""
    B, H, E, topk = 4, 128, 16, 4
    dtype = torch.float32
    
    # Create inputs with large values to test numerical stability
    x = torch.randn(B, H, dtype=dtype, device=flaggems_sglang.device) * 100
    router_weight = torch.randn(E, H, dtype=dtype, device=flaggems_sglang.device) * 100
    
    ref_weights, ref_ids = reference(x, router_weight, topk, 0.0)
    impl_weights, impl_ids = fused_moe_router_cudacore(x, router_weight, topk, 0.0)
    
    # Check for NaN or Inf
    assert not torch.isnan(impl_weights).any(), "NaN in impl_weights"
    assert not torch.isinf(impl_weights).any(), "Inf in impl_weights"
    assert not torch.isnan(impl_ids).any(), "NaN in impl_ids"
    assert not torch.isinf(impl_ids).any(), "Inf in impl_ids"
    
    # Check values
    torch.testing.assert_close(impl_ids, ref_ids, atol=0, rtol=0)
    torch.testing.assert_close(impl_weights, ref_weights, atol=1e-4, rtol=1e-4)


@pytest.mark.fused_moe_router_cudacore
def test_fused_moe_router_cudacore_weight_sum():
    """Test that topk_weights sum to approximately 1."""
    B, H, E, topk = 8, 256, 32, 4
    dtype = torch.float32
    
    x = torch.randn(B, H, dtype=dtype, device=flaggems_sglang.device)
    router_weight = torch.randn(E, H, dtype=dtype, device=flaggems_sglang.device)
    
    impl_weights, impl_ids = fused_moe_router_cudacore(x, router_weight, topk, 0.0)
    
    # Note: topk_weights are from global softmax, so they don't necessarily sum to 1
    # They are the probabilities of the selected experts from the full softmax
    # So we just check they are valid probabilities
    assert (impl_weights >= 0).all(), "Negative weights found"
    assert (impl_weights <= 1).all(), "Weights > 1 found"
