# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen


"""MetaX scan with the empirically tuned MACA launch policy."""


import torch
import triton
import triton.language as tl

__all__ = ["chunk_cumsum"]


@triton.jit
def _softplus_fp32(x):
    # max(x, 0) + log(1 + exp(-abs(x))) is stable at both tails.
    return tl.maximum(x, 0.0) + tl.log(1.0 + tl.exp(-tl.abs(x)))


@triton.jit
def _chunk_cumsum_kernel(
    dt_ptr,
    a_ptr,
    bias_ptr,
    dt_out_ptr,
    da_cumsum_ptr,
    seqlen,
    nheads,
    nchunks,
    chunk_size,
    stride_dt_b,
    stride_dt_s,
    stride_dt_h,
    stride_a_h,
    stride_bias_h,
    HAS_BIAS: tl.constexpr,
    DT_SOFTPLUS: tl.constexpr,
    BLOCK_H: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    pid_b = tl.program_id(0)
    pid_c = tl.program_id(1)
    pid_h = tl.program_id(2)

    offs_h = pid_h * BLOCK_H + tl.arange(0, BLOCK_H)
    offs_k = tl.arange(0, BLOCK_K)
    offs_s = pid_c * chunk_size + offs_k

    valid_h = offs_h < nheads
    valid_k = offs_k < chunk_size
    valid_s = offs_s < seqlen
    load_mask = valid_h[:, None] & valid_k[None, :] & valid_s[None, :]

    dt_offsets = (
        pid_b * stride_dt_b
        + offs_s[None, :] * stride_dt_s
        + offs_h[:, None] * stride_dt_h
    )
    dt = tl.load(dt_ptr + dt_offsets, mask=load_mask, other=0.0).to(tl.float32)

    if HAS_BIAS:
        bias = tl.load(
            bias_ptr + offs_h * stride_bias_h,
            mask=valid_h,
            other=0.0,
        ).to(tl.float32)
        dt += bias[:, None]

    if DT_SOFTPLUS:
        # Match torch.nn.functional.softplus's default threshold.
        dt = tl.where(dt <= 20.0, _softplus_fp32(dt), dt)

    dt = tl.maximum(dt, 0.0)
    # Bias/softplus can turn a masked zero into a nonzero; mask again.
    dt = tl.where(load_mask, dt, 0.0)

    out_offsets = (
        (pid_b * nheads + offs_h[:, None]) * nchunks + pid_c
    ) * chunk_size + offs_k[None, :]
    store_mask = valid_h[:, None] & valid_k[None, :]
    tl.store(dt_out_ptr + out_offsets, dt, mask=store_mask)

    a = tl.load(
        a_ptr + offs_h * stride_a_h,
        mask=valid_h,
        other=0.0,
    ).to(tl.float32)
    da = dt * a[:, None]
    da_cumsum = tl.cumsum(da, axis=1)
    tl.store(da_cumsum_ptr + out_offsets, da_cumsum, mask=store_mask)


@triton.jit
def _chunk_cumsum_wave64_kernel(
    dt_ptr,
    a_ptr,
    bias_ptr,
    dt_out_ptr,
    da_cumsum_ptr,
    seqlen: tl.constexpr,
    nheads: tl.constexpr,
    nchunks: tl.constexpr,
    chunk_size: tl.constexpr,
    stride_dt_b: tl.constexpr,
    stride_dt_s: tl.constexpr,
    stride_dt_h: tl.constexpr,
    stride_a_h: tl.constexpr,
    stride_bias_h: tl.constexpr,
    HAS_BIAS: tl.constexpr,
    DT_SOFTPLUS: tl.constexpr,
    BLOCK_H: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    # Triton Wave64 targets benefit from making shape and stride metadata
    # compile-time constants. This removes dynamic integer address arithmetic
    # from the scan and lets the backend simplify full-chunk boundary masks.
    pid_b = tl.program_id(0)
    pid_c = tl.program_id(1)
    pid_h = tl.program_id(2)

    offs_h = pid_h * BLOCK_H + tl.arange(0, BLOCK_H)
    offs_k = tl.arange(0, BLOCK_K)
    offs_s = pid_c * chunk_size + offs_k

    valid_h = offs_h < nheads
    valid_k = offs_k < chunk_size
    valid_s = offs_s < seqlen
    load_mask = valid_h[:, None] & valid_k[None, :] & valid_s[None, :]

    dt_offsets = (
        pid_b * stride_dt_b
        + offs_s[None, :] * stride_dt_s
        + offs_h[:, None] * stride_dt_h
    )
    dt = tl.load(dt_ptr + dt_offsets, mask=load_mask, other=0.0).to(tl.float32)

    if HAS_BIAS:
        bias = tl.load(
            bias_ptr + offs_h * stride_bias_h,
            mask=valid_h,
            other=0.0,
        ).to(tl.float32)
        dt += bias[:, None]

    if DT_SOFTPLUS:
        dt = tl.where(dt <= 20.0, _softplus_fp32(dt), dt)

    dt = tl.maximum(dt, 0.0)
    dt = tl.where(load_mask, dt, 0.0)

    out_offsets = (
        (pid_b * nheads + offs_h[:, None]) * nchunks + pid_c
    ) * chunk_size + offs_k[None, :]
    store_mask = valid_h[:, None] & valid_k[None, :]
    tl.store(dt_out_ptr + out_offsets, dt, mask=store_mask)

    a = tl.load(
        a_ptr + offs_h * stride_a_h,
        mask=valid_h,
        other=0.0,
    ).to(tl.float32)
    da_cumsum = tl.cumsum(dt * a[:, None], axis=1)
    tl.store(da_cumsum_ptr + out_offsets, da_cumsum, mask=store_mask)


def _launch_config(block_k, nheads, work, is_fp32):
    """Select shape/dtype tuning for this implementation."""
    if block_k == 256:
        if work <= 1024:
            block_h = 4 if is_fp32 else 8
        else:
            block_h = 16 if is_fp32 else 32
        num_warps = 8
    elif block_k == 128:
        if work <= 1024:
            block_h = 8 if is_fp32 else 16
            num_warps = 4 if is_fp32 else 8
        elif work <= 4096:
            (block_h, num_warps) = (16, 4)
        else:
            block_h = 16 if is_fp32 else 32
            num_warps = 4
    elif block_k <= 64:
        if work <= 512:
            (block_h, num_warps) = (16, 8)
        elif work <= 4096:
            (block_h, num_warps) = (16, 4)
        else:
            block_h = 32
            num_warps = 4 if is_fp32 else 2
    else:
        block_h = max(1, 1024 // block_k)
        num_warps = 8
    return (min(block_h, triton.next_power_of_2(nheads)), num_warps)


def chunk_cumsum(dt, A, chunk_size, dt_bias=None, dt_softplus=False):
    """Triton implementation of Mamba's chunk-wise dt/A cumulative sum."""
    if dt.ndim != 3:
        raise ValueError("dt must have shape [batch, seqlen, nheads]")
    if chunk_size <= 0:
        raise ValueError("chunk_size must be positive")
    (batch, seqlen, nheads) = dt.shape
    if seqlen == 0 or nheads == 0 or batch == 0:
        raise ValueError("dt dimensions must be nonzero")
    if A.ndim != 1 or A.shape[0] != nheads:
        raise ValueError("A must have shape [nheads]")
    if dt_bias is not None and (
        dt_bias.ndim != 1 or dt_bias.shape[0] != nheads
    ):
        raise ValueError("dt_bias must have shape [nheads]")
    nchunks = (seqlen + chunk_size - 1) // chunk_size
    out_shape = (batch, nheads, nchunks, chunk_size)
    dt_out = torch.empty(out_shape, device=dt.device, dtype=torch.float32)
    da_cumsum = torch.empty(out_shape, device=dt.device, dtype=torch.float32)
    block_k = triton.next_power_of_2(chunk_size)
    bias_ptr = dt if dt_bias is None else dt_bias
    work = batch * nchunks * nheads
    (block_h, num_warps) = _launch_config(
        block_k, nheads, work, dt.dtype == torch.float32
    )
    grid = (batch, nchunks, triton.cdiv(nheads, block_h))
    # Tiny scans retain the compact generic kernel.
    use_wide_wave_kernel = not (block_k <= 64 and work <= 512)
    kernel = (
        _chunk_cumsum_wave64_kernel
        if use_wide_wave_kernel
        else _chunk_cumsum_kernel
    )
    kernel[grid](
        dt,
        A,
        bias_ptr,
        dt_out,
        da_cumsum,
        seqlen,
        nheads,
        nchunks,
        chunk_size,
        dt.stride(0),
        dt.stride(1),
        dt.stride(2),
        A.stride(0),
        0 if dt_bias is None else dt_bias.stride(0),
        HAS_BIAS=dt_bias is not None,
        DT_SOFTPLUS=dt_softplus,
        BLOCK_H=block_h,
        BLOCK_K=block_k,
        num_warps=num_warps,
    )
    return (dt_out, da_cumsum)
