# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen


"""Ascend relayout and loop scan with bounded UB tiles."""


import torch
import triton
import triton.language as tl

__all__ = ["chunk_cumsum"]


@triton.jit
def _softplus_fp32(x):
    # max(x, 0) + log(1 + exp(-abs(x))) is stable at both tails.
    return tl.maximum(x, 0.0) + tl.log(1.0 + tl.exp(-tl.abs(x)))


@triton.jit
def _chunk_dt_relayout_kernel(
    dt_ptr,
    bias_ptr,
    dt_out_ptr,
    seqlen,
    nheads,
    nchunks,
    chunk_size,
    stride_dt_b,
    stride_dt_s,
    stride_dt_h,
    stride_bias_h,
    HAS_BIAS: tl.constexpr,
    DT_SOFTPLUS: tl.constexpr,
    BLOCK_S: tl.constexpr,
    BLOCK_H: tl.constexpr,
):
    # Load [sequence, head] contiguously, transform in UB, then transpose to
    # the output's [head, sequence] layout before storing.
    pid_b = tl.program_id(0)
    pid_s = tl.program_id(1)
    pid_hb = tl.program_id(2)

    offs_s = pid_s * BLOCK_S + tl.arange(0, BLOCK_S)
    offs_h = pid_hb * BLOCK_H + tl.arange(0, BLOCK_H)
    padded_seqlen = nchunks * chunk_size
    valid_s = offs_s < padded_seqlen
    valid_h = offs_h < nheads
    load_mask = (offs_s[:, None] < seqlen) & valid_h[None, :]

    dt_offsets = (
        pid_b * stride_dt_b
        + offs_s[:, None] * stride_dt_s
        + offs_h[None, :] * stride_dt_h
    )
    dt = tl.load(dt_ptr + dt_offsets, mask=load_mask, other=0.0).to(tl.float32)

    if HAS_BIAS:
        bias = tl.load(
            bias_ptr + offs_h * stride_bias_h,
            mask=valid_h,
            other=0.0,
        ).to(tl.float32)
        dt += bias[None, :]

    if DT_SOFTPLUS:
        dt = tl.where(dt <= 20.0, _softplus_fp32(dt), dt)

    dt = tl.maximum(dt, 0.0)
    dt = tl.where(load_mask, dt, 0.0)

    out_offsets = (pid_b * nheads + offs_h[:, None]) * padded_seqlen + offs_s[
        None, :
    ]
    store_mask = valid_h[:, None] & valid_s[None, :]
    tl.store(dt_out_ptr + out_offsets, tl.trans(dt), mask=store_mask)


@triton.jit(do_not_specialize=["chunk_size", "total_rows"])
def _chunk_scan_npu_manual_loop_kernel(
    dt_out_ptr,
    a_ptr,
    da_cumsum_ptr,
    total_rows,
    nheads: tl.constexpr,
    nchunks: tl.constexpr,
    chunk_size,
    stride_a_h: tl.constexpr,
    BLOCK_R: tl.constexpr,
):
    # Avoid Ascend ScanOp completely. Each lane carries one recurrence state
    # while a runtime loop walks its contiguous output row.
    pid = tl.program_id(0)
    rows = pid * BLOCK_R + tl.arange(0, BLOCK_R)
    valid_rows = rows < total_rows
    h = (rows // nchunks) % nheads
    a = tl.load(a_ptr + h * stride_a_h, mask=valid_rows, other=0.0).to(
        tl.float32
    )
    running = tl.zeros((BLOCK_R,), tl.float32)
    for k in range(0, chunk_size):
        offsets = rows * chunk_size + k
        dt = tl.load(dt_out_ptr + offsets, mask=valid_rows, other=0.0).to(
            tl.float32
        )
        running += dt * a
        tl.store(da_cumsum_ptr + offsets, running, mask=valid_rows)


def chunk_cumsum(dt, A, chunk_size, dt_bias=None, dt_softplus=False):
    """Triton implementation of Mamba's chunk-wise dt/A cumulative sum."""
    if dt.ndim != 3:
        raise ValueError("dt must have shape [batch, seqlen, nheads]")
    if chunk_size <= 0:
        raise ValueError("chunk_size must be positive")
    (batch, seqlen, nheads) = dt.shape
    if seqlen == 0 or nheads == 0 or batch == 0:
        raise ValueError("dt dimensions must be nonzero")
    if A.ndim != 1 or A.shape[0] != nheads:
        raise ValueError("A must have shape [nheads]")
    if dt_bias is not None and (
        dt_bias.ndim != 1 or dt_bias.shape[0] != nheads
    ):
        raise ValueError("dt_bias must have shape [nheads]")
    nchunks = (seqlen + chunk_size - 1) // chunk_size
    out_shape = (batch, nheads, nchunks, chunk_size)
    dt_out = torch.empty(out_shape, device=dt.device, dtype=torch.float32)
    da_cumsum = torch.empty(out_shape, device=dt.device, dtype=torch.float32)
    bias_ptr = dt if dt_bias is None else dt_bias
    # Limit each relayout tile to 8192 elements to bound UB usage.
    npu_dt_block_h = min(64, triton.next_power_of_2(nheads))
    npu_dt_block_s = min(512, 8192 // npu_dt_block_h)
    padded_seqlen = nchunks * chunk_size
    npu_dt_grid = (
        batch,
        triton.cdiv(padded_seqlen, npu_dt_block_s),
        triton.cdiv(nheads, npu_dt_block_h),
    )
    _chunk_dt_relayout_kernel[npu_dt_grid](
        dt,
        bias_ptr,
        dt_out,
        seqlen,
        nheads,
        nchunks,
        chunk_size,
        dt.stride(0),
        dt.stride(1),
        dt.stride(2),
        0 if dt_bias is None else dt_bias.stride(0),
        HAS_BIAS=dt_bias is not None,
        DT_SOFTPLUS=dt_softplus,
        BLOCK_S=npu_dt_block_s,
        BLOCK_H=npu_dt_block_h,
        num_warps=4,
    )
    total_rows = batch * nheads * nchunks
    if total_rows <= 1024:
        preferred_block_r = 16
    elif total_rows <= 4096:
        preferred_block_r = 32
    else:
        preferred_block_r = 64
    npu_scan_block_r = min(
        preferred_block_r, triton.next_power_of_2(total_rows)
    )
    npu_scan_grid = (triton.cdiv(total_rows, npu_scan_block_r),)
    _chunk_scan_npu_manual_loop_kernel[npu_scan_grid](
        dt_out,
        A,
        da_cumsum,
        total_rows,
        nheads,
        nchunks,
        chunk_size,
        A.stride(0),
        BLOCK_R=npu_scan_block_r,
        num_warps=4,
    )
    return (dt_out, da_cumsum)
