# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

"""Operator: activation_norm/silu_and_mul (Ascend/Huawei placeholder).

Vendor specialization for Ascend NPU. This override sits at priority
level 1 and will replace the generic tier when running on Ascend hardware.
Replace the body of :func:`silu_and_mul` with an Ascend-optimized
implementation (e.g. leveraging CANN intrinsics or AscendC).
"""

import torch


def silu_and_mul(hidden_states: torch.Tensor) -> torch.Tensor:
    """Gated SiLU: ``silu(x[..., :d]) * x[..., d:]`` (Ascend).

    Args:
        hidden_states: Input tensor with an even last dimension.

    Returns:
        Tensor with the last dim halved, same dtype as ``hidden_states``.
    """
    raise NotImplementedError(
        "silu_and_mul Ascend specialization is not implemented yet."
    )


__all__ = ["silu_and_mul"]
