# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen


"""Enflame scan with GCU launch tuning and a capped persistent grid."""


import torch
import triton
import triton.language as tl

__all__ = ["chunk_cumsum"]


@triton.jit
def _softplus_fp32(x):
    # max(x, 0) + log(1 + exp(-abs(x))) is stable at both tails.
    return tl.maximum(x, 0.0) + tl.log(1.0 + tl.exp(-tl.abs(x)))


@triton.jit
def _chunk_cumsum_kernel(
    dt_ptr,
    a_ptr,
    bias_ptr,
    dt_out_ptr,
    da_cumsum_ptr,
    seqlen,
    nheads,
    nchunks,
    chunk_size,
    stride_dt_b,
    stride_dt_s,
    stride_dt_h,
    stride_a_h,
    stride_bias_h,
    HAS_BIAS: tl.constexpr,
    DT_SOFTPLUS: tl.constexpr,
    BLOCK_H: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    pid_b = tl.program_id(0)
    pid_c = tl.program_id(1)
    pid_h = tl.program_id(2)

    offs_h = pid_h * BLOCK_H + tl.arange(0, BLOCK_H)
    offs_k = tl.arange(0, BLOCK_K)
    offs_s = pid_c * chunk_size + offs_k

    valid_h = offs_h < nheads
    valid_k = offs_k < chunk_size
    valid_s = offs_s < seqlen
    load_mask = valid_h[:, None] & valid_k[None, :] & valid_s[None, :]

    dt_offsets = (
        pid_b * stride_dt_b
        + offs_s[None, :] * stride_dt_s
        + offs_h[:, None] * stride_dt_h
    )
    dt = tl.load(dt_ptr + dt_offsets, mask=load_mask, other=0.0).to(tl.float32)

    if HAS_BIAS:
        bias = tl.load(
            bias_ptr + offs_h * stride_bias_h,
            mask=valid_h,
            other=0.0,
        ).to(tl.float32)
        dt += bias[:, None]

    if DT_SOFTPLUS:
        # Match torch.nn.functional.softplus's default threshold.
        dt = tl.where(dt <= 20.0, _softplus_fp32(dt), dt)

    dt = tl.maximum(dt, 0.0)
    # Bias/softplus can turn a masked zero into a nonzero; mask again.
    dt = tl.where(load_mask, dt, 0.0)

    out_offsets = (
        (pid_b * nheads + offs_h[:, None]) * nchunks + pid_c
    ) * chunk_size + offs_k[None, :]
    store_mask = valid_h[:, None] & valid_k[None, :]
    tl.store(dt_out_ptr + out_offsets, dt, mask=store_mask)

    a = tl.load(
        a_ptr + offs_h * stride_a_h,
        mask=valid_h,
        other=0.0,
    ).to(tl.float32)
    da = dt * a[:, None]
    da_cumsum = tl.cumsum(da, axis=1)
    tl.store(da_cumsum_ptr + out_offsets, da_cumsum, mask=store_mask)


@triton.jit
def _chunk_cumsum_gcu_loop_kernel(
    dt_ptr,
    a_ptr,
    bias_ptr,
    dt_out_ptr,
    da_cumsum_ptr,
    seqlen,
    nheads,
    nchunks,
    chunk_size,
    stride_dt_b,
    stride_dt_s,
    stride_dt_h,
    stride_a_h,
    stride_bias_h,
    total_tiles,
    HAS_BIAS: tl.constexpr,
    DT_SOFTPLUS: tl.constexpr,
    BLOCK_H: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    # GCU300 has 24 physical clusters. Cap the launch at one program per
    # cluster and consume additional independent [head, chunk] tiles on-device.
    pid = tl.program_id(0)
    step = tl.num_programs(0)
    num_hblocks = tl.cdiv(nheads, BLOCK_H)
    for tile_id in tl.range(pid, total_tiles, step):
        pid_h = tile_id % num_hblocks
        tile_bc = tile_id // num_hblocks
        pid_c = tile_bc % nchunks
        pid_b = tile_bc // nchunks

        offs_h = pid_h * BLOCK_H + tl.arange(0, BLOCK_H)
        offs_k = tl.arange(0, BLOCK_K)
        offs_s = pid_c * chunk_size + offs_k
        valid_h = offs_h < nheads
        valid_k = offs_k < chunk_size
        valid_s = offs_s < seqlen
        load_mask = valid_h[:, None] & valid_k[None, :] & valid_s[None, :]

        dt_offsets = (
            pid_b * stride_dt_b
            + offs_s[None, :] * stride_dt_s
            + offs_h[:, None] * stride_dt_h
        )
        dt = tl.load(dt_ptr + dt_offsets, mask=load_mask, other=0.0).to(
            tl.float32
        )
        if HAS_BIAS:
            bias = tl.load(
                bias_ptr + offs_h * stride_bias_h,
                mask=valid_h,
                other=0.0,
            ).to(tl.float32)
            dt += bias[:, None]
        if DT_SOFTPLUS:
            dt = tl.where(dt <= 20.0, _softplus_fp32(dt), dt)
        dt = tl.maximum(dt, 0.0)
        dt = tl.where(load_mask, dt, 0.0)

        out_offsets = (
            (pid_b * nheads + offs_h[:, None]) * nchunks + pid_c
        ) * chunk_size + offs_k[None, :]
        store_mask = valid_h[:, None] & valid_k[None, :]
        tl.store(dt_out_ptr + out_offsets, dt, mask=store_mask)

        a = tl.load(
            a_ptr + offs_h * stride_a_h,
            mask=valid_h,
            other=0.0,
        ).to(tl.float32)
        da_cumsum = tl.cumsum(dt * a[:, None], axis=1)
        tl.store(da_cumsum_ptr + out_offsets, da_cumsum, mask=store_mask)


def _launch_config(block_k, nheads, work):
    """Select shape/dtype tuning for this implementation."""
    min_block_h = max(1, 512 // block_k)
    max_block_h = max(1, 32768 // block_k)
    block_h = max(
        min_block_h, min(triton.next_power_of_2(nheads), max_block_h)
    )
    return (block_h, 2 if work <= 1024 else 1)


def chunk_cumsum(dt, A, chunk_size, dt_bias=None, dt_softplus=False):
    """Triton implementation of Mamba's chunk-wise dt/A cumulative sum."""
    if dt.ndim != 3:
        raise ValueError("dt must have shape [batch, seqlen, nheads]")
    if chunk_size <= 0:
        raise ValueError("chunk_size must be positive")
    (batch, seqlen, nheads) = dt.shape
    if seqlen == 0 or nheads == 0 or batch == 0:
        raise ValueError("dt dimensions must be nonzero")
    if A.ndim != 1 or A.shape[0] != nheads:
        raise ValueError("A must have shape [nheads]")
    if dt_bias is not None and (
        dt_bias.ndim != 1 or dt_bias.shape[0] != nheads
    ):
        raise ValueError("dt_bias must have shape [nheads]")
    nchunks = (seqlen + chunk_size - 1) // chunk_size
    out_shape = (batch, nheads, nchunks, chunk_size)
    dt_out = torch.empty(out_shape, device=dt.device, dtype=torch.float32)
    da_cumsum = torch.empty(out_shape, device=dt.device, dtype=torch.float32)
    block_k = triton.next_power_of_2(chunk_size)
    bias_ptr = dt if dt_bias is None else dt_bias
    work = batch * nchunks * nheads
    (block_h, num_warps) = _launch_config(block_k, nheads, work)
    if block_k == 256 and block_h <= 64 and (work > 1024):
        num_hblocks = triton.cdiv(nheads, block_h)
        total_tiles = batch * nchunks * num_hblocks
        _chunk_cumsum_gcu_loop_kernel[min(total_tiles, 24),](
            dt,
            A,
            bias_ptr,
            dt_out,
            da_cumsum,
            seqlen,
            nheads,
            nchunks,
            chunk_size,
            dt.stride(0),
            dt.stride(1),
            dt.stride(2),
            A.stride(0),
            0 if dt_bias is None else dt_bias.stride(0),
            total_tiles,
            HAS_BIAS=dt_bias is not None,
            DT_SOFTPLUS=dt_softplus,
            BLOCK_H=block_h,
            BLOCK_K=block_k,
            num_warps=num_warps,
        )
        return (dt_out, da_cumsum)
    grid = (batch, nchunks, triton.cdiv(nheads, block_h))
    _chunk_cumsum_kernel[grid](
        dt,
        A,
        bias_ptr,
        dt_out,
        da_cumsum,
        seqlen,
        nheads,
        nchunks,
        chunk_size,
        dt.stride(0),
        dt.stride(1),
        dt.stride(2),
        A.stride(0),
        0 if dt_bias is None else dt_bias.stride(0),
        HAS_BIAS=dt_bias is not None,
        DT_SOFTPLUS=dt_softplus,
        BLOCK_H=block_h,
        BLOCK_K=block_k,
        num_warps=num_warps,
    )
    return (dt_out, da_cumsum)
